from .doc3_3_get_xbrl_financial_statements import Docstring_get_xbrl_financial_statements
from .doc3_4_get_complete_financial_statements import Docstring_get_complete_financial_statements
from .doc3_5_get_xbrl_taxonomy_format import Docstring_get_xbrl_taxonomy_format
from .doc3_6_get_single_company_key_indicators import Docstring_get_single_company_key_indicators